### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by valenbase** [hmakelin/gisnav#139]
Great Work!

Could you tell me the system env for you to compile and run?

My system setting is :
- ubuntu 20.04
- ros noetic & ros foxy

I meet the problem
```
ERROR [nmea 5/7] RUN rosdep update &&     apt-get update &&     rosdep install --from-paths ./src -y -r --ignore-src &&     rm -rf /var/lib/apt/lists/* &&     apt clean
```
But I parse the line to the terminal the command works well

**Comment by valenbase** [comment]
Is it possible to run the demo without docker?

**Comment by valenbase** [comment]
I saw the markdown files in docs, I will try.

**Comment by hmakelin** [comment]
Thank you for reporting - some information below for reference:

> Could you tell me the system env for you to compile and run?

I use Ubuntu 22.04 Jammy and ROS 2 Humble on my development machine.

> Is it possible to run the demo without docker?

I no longer have instructions for setting up all of the supporting services locally as there are so many. Practically speaking to run the demo you will need to build the Docker images.

There are also so many Compose override files for setting up the services that the instructions assume you will use the CLI (`gnc`) tool to build and run them. There is more information on installing and using the CLI in the guide.
